Repository kowainik/tomland, pull requests merged in 2018-05, with the labels that each got.

#35 [#31] Change TOML to use PrefixMap
  examples/Playground.hs
  src/Toml/Parser.hs
  src/Toml/PrefixTree.hs
  src/Toml/Printer.hs
  src/Toml/Type.hs
  test.toml
Labels: PrefixTree, ast, parser, pretty-printer

#34 [#32] Add InsertLookup property test for PrefixTree
  src/Toml/PrefixTree.hs
  stack-8.0.2.yaml
  stack.yaml
  test/Spec.hs
  test/Test/Toml/PrefixTree.hs
  test/Test/Toml/PrefixTree/Property.hs
  test/Test/Toml/PrefixTree/Unit.hs
  tomland.cabal
Labels: PrefixTree, test

#36 [#25] Implement basic bidirectional Toml conversion
  examples/Playground.hs
  examples/biTest.toml
  src/Toml.hs
  src/Toml/Bi.hs
  src/Toml/Bi/Combinators.hs
  src/Toml/Bi/Monad.hs
  src/Toml/Parser.hs
  tomland.cabal
Labels: bi

#41 Make it more usable
  CHANGELOG.md
  examples/Playground.hs
  examples/biTest.toml
  src/Toml/Bi/Combinators.hs
  src/Toml/Bi/Monad.hs
  src/Toml/Parser.hs
  src/Toml/PrefixTree.hs
  src/Toml/Type.hs
  test.toml
  tomland.cabal
Labels: bi, parser, λ-safe

#45 [#44] Add bidirectional converter for Maybe
  CHANGELOG.md
  examples/Playground.hs
  src/Toml.hs
  src/Toml/Bi/Combinators.hs
Labels: bi

#49 [#47] Introduce mdimap combinator
  CHANGELOG.md
  examples/Playground.hs
  src/Toml/Bi/Combinators.hs
  src/Toml/Bi/Monad.hs
  tomland.cabal
Labels: bi

#51 [#37] Add table support to bi
  CHANGELOG.md
  examples/Playground.hs
  examples/biTest.toml
  src/Toml/Bi/Combinators.hs
Labels: bi, λ-safe

#52 [#39] Pretty exceptions
  CHANGELOG.md
  examples/Playground.hs
  examples/biTest.toml
  src/Toml/Bi.hs
  src/Toml/Bi/Code.hs
  src/Toml/Bi/Combinators.hs
  src/Toml/PrefixTree.hs
  src/Toml/Type.hs
  tomland.cabal
Labels: bi, pretty-printer
