Repository kowainik/tomland, pull requests merged in 2018-03, with the labels that each got.

#2 [#1] Implement basic version of TOML
  CHANGELOG.md
  src/Lib.hs
  src/Toml.hs
  src/Toml/Parser.hs
  src/Toml/Type.hs
  stack.yaml
  tomland.cabal
Labels: ast

#6 [#4] Add basic pretty-printer
  examples/Playground.hs
  src/Toml/Printer.hs
  tomland.cabal
Labels: pretty-printer

#9 [#7] Implement type-safe Value
  examples/Playground.hs
  src/Toml/Printer.hs
  src/Toml/Type.hs
Labels: ast, λ-safe
