Repository kowainik/tomland, pull requests merged in 2018-11, with the labels that each got.

#126 [#122] Boil htoml for benchmark
  benchmark/Benchmark/Htoml.hs
  benchmark/Benchmark/Tomland.hs
  benchmark/Benchmark/Type.hs
  benchmark/Main.hs
  benchmark/benchmark.toml
  src/Toml/Bi/Code.hs
  src/Toml/Parser.hs
  src/Toml/PrefixTree.hs
  src/Toml/Type/AnyValue.hs
  src/Toml/Type/TOML.hs
  src/Toml/Type/Value.hs
  tomland.cabal
Labels: Hacktoberfest, performance

#136 [#130] Added combinators
  CHANGELOG.md
  src/Toml/Bi/Combinators.hs
  src/Toml/BiMap.hs
  src/Toml/Type/AnyValue.hs
Labels: codec

#138 Prepare for 0.5.0 release
  .travis.yml
  CHANGELOG.md
  stack.yaml
  tomland.cabal
Labels: doc

#132 [#131] Uncommenting tomlTableArrays
  CHANGELOG.md
  src/Toml/Parser/TOML.hs
  src/Toml/Type/TOML.hs
  test/Test/Toml/Gen.hs
  test/Test/Toml/Parsing/Unit.hs
Labels: ast

#142 [#133] Patching EDSL for arrays of tables
  CHANGELOG.md
  src/Toml/Edsl.hs
Labels: codec

#148 [#140] Change the type of wrapper function
  CHANGELOG.md
  examples/Playground.hs
  src/Toml/Bi/Combinators.hs
  src/Toml/Bi/Monad.hs
Labels: codec

#150 [#149] Removing record syntax from PrefixTree
  CHANGELOG.md
  examples/Playground.hs
  src/Toml/PrefixTree.hs
Labels: ast

#156 [#152] Remove mdimap
  CHANGELOG.md
  src/Toml/Bi/Combinators.hs
Labels: codec

#128 [#64] No leading zeros
  CHANGELOG.md
  benchmark/Benchmark/Tomland.hs
  benchmark/Benchmark/Type.hs
  benchmark/benchmark.toml
  src/Toml/Parser/Core.hs
  src/Toml/Parser/Value.hs
  test/Test/Toml/Parsing/Unit.hs
Labels: parser
