Repository kowainik/tomland, pull requests merged in 2018-10, with the labels that each got.

#96 [#90] Migrate to megaparsec 7
  CHANGELOG.md
  src/Toml/Parser.hs
  stack.yaml
  tomland.cabal
Labels: Hacktoberfest, parser

#97 [#17] Allow underscores in integers
  CHANGELOG.md
  src/Toml/Parser.hs
  test/Test/Toml/Parsing/Unit.hs
Labels: Hacktoberfest, parser, test

#101 [#82] Remove maybeT, add diOptional
  CHANGELOG.md
  examples/Playground.hs
  src/Toml/Bi/Combinators.hs
  src/Toml/Bi/Monad.hs
  tomland.cabal
Labels: Hacktoberfest, bug, refactoring

#103 Add golden tests for pretty printer
  .gitattributes
  src/Toml/PrefixTree.hs
  src/Toml/Printer.hs
  test/Test/Toml/Printer/Golden.hs
  test/golden/pretty_default.golden
  test/golden/pretty_indented_only.golden
  test/golden/pretty_sorted_only.golden
  test/golden/pretty_unformatted.golden
  tomland.cabal
Labels: Hacktoberfest, pretty-printer, test

#104 [Issue #70] Added function to create BiMap from concrete types
  CHANGELOG.md
  src/Toml/BiMap.hs
Labels: Hacktoberfest, codec

#106 [Issue #95 ]Reversed BiMap Anything a into BiMap a Anything
  CHANGELOG.md
  examples/Playground.hs
  src/Toml/Bi/Combinators.hs
  src/Toml/BiMap.hs
Labels: Hacktoberfest, codec, refactoring

#112 [#109] Add `decodeToml` function
  CHANGELOG.md
  src/Toml/Bi/Code.hs
Labels: codec

#113 [#22] Report proper type checking error during parsing
  CHANGELOG.md
  src/Toml/Parser.hs
Labels: Hacktoberfest, parser

#116 [#99] Split `Toml.Parser` file into smaller files
  CHANGELOG.md
  src/Toml/Parser.hs
  src/Toml/Parser/Core.hs
  src/Toml/Parser/TOML.hs
  src/Toml/Parser/Value.hs
  test/Test/Toml/Parsing/Unit.hs
  tomland.cabal
Labels: Hacktoberfest, refactoring

#107 [Issue #59] Adding a bunch of BiMaps
  src/Toml/BiMap.hs
  tomland.cabal
Labels: Hacktoberfest, codec

#120 [#118] more container bimaps
  src/Toml/Bi/Combinators.hs
  src/Toml/BiMap.hs
  tomland.cabal
Labels: Hacktoberfest

#114 [#110] Example of TOML for the benchmarks
  CHANGELOG.md
  benchmark/Benchmark/Type.hs
  benchmark/Main.hs
  benchmark/benchmark.toml
  src/Toml/Bi/Monad.hs
  tomland.cabal
Labels: Hacktoberfest, performance
