Repository kowainik/tomland, pull requests merged in 2018-07, with the labels that each got.

#73 [#23] Use cabal on travis, upgrade to lts-12.0
  .travis.yml
  stack-8.0.2.yaml
  stack-8.4.2.yaml
  stack.yaml
  tomland.cabal
Labels: build

#71 [#40] Support full-featured string parser
  CHANGELOG.md
  src/Toml/Parser.hs
  test/Test/Toml/Parsing/Unit.hs
Labels: parser

#75 Add `Alternative` instance for `Bijection`
  src/Toml/Bi/Code.hs
  src/Toml/Bi/Combinators.hs
  src/Toml/Bi/Monad.hs
  tomland.cabal
Labels: bi, question

#74 [#18] Add dates parsing
  CHANGELOG.md
  src/Toml/Parser.hs
  test/Test/Toml/Parsing/Unit.hs
Labels: parser

#78 [#58] Add decodeFile function
  CHANGELOG.md
  src/Toml/Bi/Code.hs
Labels: parser
