Repository kowainik/tomland, pull requests merged in 2019-07, with the labels that each got.

#200 [#154] Implement generic codec
  src/Toml.hs
  src/Toml/Bi/Map.hs
  src/Toml/Generic.hs
  test/Test/Toml/BiCode/Property.hs
  tomland.cabal
Labels: codec

#205 Prepare 1.1.0.0 release
  CHANGELOG.md
  src/Toml/Bi/Combinators.hs
  src/Toml/Bi/Map.hs
  src/Toml/Generic.hs
  src/Toml/Printer.hs
  tomland.cabal
Labels: doc

#208 [#206] Test on toml-v0.4.0 example
  CHANGELOG.md
  src/Toml/Parser/TOML.hs
  test/Test/Toml/Parsing/Examples.hs
  test/Test/Toml/Parsing/Unit.hs
  test/examples/example-v0.3.0.toml
  test/examples/example-v0.4.0.toml
  test/examples/example.toml
  test/examples/fruit.toml
  test/examples/hard_example.toml
  test/examples/hard_example_unicode.toml
  tomland.cabal
Labels: bug, parser

#210 [#209] Bump up parser-combinators to 1.2.0
  .gitignore
  stack.yaml
  tomland.cabal
Labels: library
