Repository kowainik/tomland, pull requests merged in 2019-10, with the labels that each got.

#221 Cleanup some metadata
  .travis.yml
  src/Toml/Parser/Key.hs
  tomland.cabal
Labels: refactoring

#222 Add combinators set and hashSet for array of tables
  README.md
  examples/Playground.hs
  src/Toml/Bi/Combinators.hs
  src/Toml/Generic.hs
  tomland.cabal
Labels: codec

#225 Avoid to generate text with ending backslash
  test/Test/Toml/Gen.hs
Labels: test

#224 [#204] Add _ByteStringArray bimap
  src/Toml/Bi/Combinators.hs
  src/Toml/Bi/Map.hs
  src/Toml/Generic.hs
  test/Test/Toml/BiMap/Property.hs
  test/Test/Toml/Gen.hs
Labels: codec

#228 [#227] Proper newline handling in parser
  src/Toml/Parser/Key.hs
Labels: parser

#229 [#226] Add dimatch combinator for sum types
  README.md
  examples/Playground.hs
  examples/biTest.toml
  src/Toml/Bi/Monad.hs
Labels: Hacktoberfest, codec

#232 Add GitHub Actions using cachix
  .github/workflows/build.yml
  .gitignore
  README.md
  default.nix
Labels: build

#233 [#230] Add AppVeyor CI
  README.md
  appveyor.yml
  examples/Main.hs
  test/Test/Toml/Gen.hs
  tomland.cabal
Labels: build

#234 Prepare for 1.2.0.0 release
  CHANGELOG.md
  src/Toml/Bi/Combinators.hs
  src/Toml/Bi/Map.hs
  src/Toml/Bi/Monad.hs
  src/Toml/Generic.hs
  src/Toml/Parser/Item.hs
  src/Toml/Parser/Key.hs
  src/Toml/Parser/Validate.hs
  stack.yaml
Labels: doc

#235 [#217] Move parsing specs to separate modules
  test/Test/Toml/Parsing/Unit.hs
  test/Test/Toml/Parsing/Unit/Array.hs
  test/Test/Toml/Parsing/Unit/Bool.hs
  test/Test/Toml/Parsing/Unit/Common.hs
  test/Test/Toml/Parsing/Unit/Date.hs
  test/Test/Toml/Parsing/Unit/Double.hs
  test/Test/Toml/Parsing/Unit/Integer.hs
  test/Test/Toml/Parsing/Unit/Key.hs
  test/Test/Toml/Parsing/Unit/Text.hs
  test/Test/Toml/Parsing/Unit/Toml.hs
  tomland.cabal
Labels: refactoring, test

#236 [#217] Use TOML Edsl, remove redundant utility functions in tests
  test/Test/Toml/Parsing/Unit/Common.hs
  test/Test/Toml/Parsing/Unit/Key.hs
  test/Test/Toml/Parsing/Unit/Toml.hs
Labels: refactoring, test

#238 Update OSS maintenance info
  .github/CODEOWNERS
  src/Toml.hs
  src/Toml/Bi.hs
  src/Toml/Bi/Code.hs
  src/Toml/Bi/Combinators.hs
  src/Toml/Bi/Map.hs
  src/Toml/Bi/Monad.hs
  src/Toml/Edsl.hs
  src/Toml/Generic.hs
  src/Toml/Parser.hs
  src/Toml/Parser/Core.hs
  src/Toml/Parser/Item.hs
  src/Toml/Parser/Key.hs
  src/Toml/Parser/String.hs
  src/Toml/Parser/Validate.hs
  src/Toml/Parser/Value.hs
  src/Toml/PrefixTree.hs
  src/Toml/Printer.hs
  src/Toml/Type.hs
  src/Toml/Type/AnyValue.hs
  src/Toml/Type/TOML.hs
  src/Toml/Type/UValue.hs
  src/Toml/Type/Value.hs
Labels: doc
