Repository kowainik/tomland, pull requests merged in 2019-01, with the labels that each got.

#153 [#137] Replace Maybe with Either in BiMap
  CHANGELOG.md
  src/Toml/Bi/Code.hs
  src/Toml/Bi/Combinators.hs
  src/Toml/BiMap.hs
  src/Toml/Type/AnyValue.hs
  src/Toml/Type/Value.hs
  test/Test/Toml/Gen.hs
Labels: refactoring

#160 [#137] Improve error messsages and refactor code
  src/Toml.hs
  src/Toml/Bi.hs
  src/Toml/Bi/Code.hs
  src/Toml/Bi/Combinators.hs
  src/Toml/Bi/Map.hs
  src/Toml/Type/AnyValue.hs
  test/Test/Toml/Gen.hs
  tomland.cabal
Labels: codec, refactoring

#151 [#134] Pretty printer for table arrays
  CHANGELOG.md
  src/Toml/Parser/Value.hs
  src/Toml/Printer.hs
  test/Test/Toml/PrefixTree/Property.hs
  test/Test/Toml/Printer/Golden.hs
  test/golden/pretty_default.golden
  test/golden/pretty_indented_only.golden
  test/golden/pretty_sorted_only.golden
  test/golden/pretty_unformatted.golden
Labels: pretty-printer

#158 [#119] Add property-based tests for BiMap
  CHANGELOG.md
  src/Toml/Bi/Map.hs
  test/Test/Toml/BiMap/Property.hs
  test/Test/Toml/Gen.hs
  tomland.cabal
Labels: test

#127 [#143] Parser for array of tables
  CHANGELOG.md
  src/Toml/Parser/TOML.hs
  src/Toml/Parser/Value.hs
  src/Toml/PrefixTree.hs
  test/Test/Toml/Parsing/Unit.hs
Labels: Hacktoberfest, parser

#165 [#144] Added tests for Arrays of Tables
  CHANGELOG.md
  test/Test/Toml/Gen.hs
  test/Test/Toml/Parsing/Unit.hs
Labels: test

#168 [#163] Move dates from DateTime
  examples/Playground.hs
  src/Toml/Bi/Map.hs
  src/Toml/Parser/Value.hs
  src/Toml/Printer.hs
  src/Toml/Type/AnyValue.hs
  src/Toml/Type/UValue.hs
  src/Toml/Type/Value.hs
  test/Test/Toml/Gen.hs
  test/Test/Toml/Parsing/Unit.hs
Labels: refactoring

#166 Add benchmarks with toml-parser library
  benchmark/Benchmark/Htoml.hs
  benchmark/Benchmark/HtomlMegaparsec.hs
  benchmark/Benchmark/TomlParser.hs
  benchmark/Benchmark/Tomland.hs
  benchmark/Benchmark/Type.hs
  benchmark/Main.hs
  stack.yaml
  tomland.cabal
Labels: performance

#169 [#155] Implement 'list' combinator (and improve docs)
  examples/Playground.hs
  examples/biTest.toml
  src/Toml/Bi.hs
  src/Toml/Bi/Combinators.hs
  src/Toml/Bi/Monad.hs
Labels: codec, doc

#170 Refactor Parsing unit tests
  test/Test/Toml/Parsing/Unit.hs
Labels: refactoring

#161 [#43] Introduce LHS readme with usage example
  README.lhs
  README.md
  examples/Playground.hs
  examples/readme.toml
  examples/test.toml
  src/Toml/Bi/Map.hs
  tomland.cabal
Labels: doc

#171 Refactor parsing modules
  src/Toml/Parser.hs
  src/Toml/Parser/Core.hs
  src/Toml/Parser/String.hs
  src/Toml/Parser/TOML.hs
  src/Toml/Parser/Value.hs
  test/Test/Toml/Parsing/Unit.hs
  tomland.cabal
Labels: parser, refactoring

#175 Improve all documentation for tomland and fix all Haddock warnings
  src/Toml.hs
  src/Toml/Bi/Code.hs
  src/Toml/Bi/Combinators.hs
  src/Toml/Bi/Map.hs
  src/Toml/Bi/Monad.hs
  src/Toml/Edsl.hs
  src/Toml/Parser.hs
  src/Toml/PrefixTree.hs
  src/Toml/Printer.hs
  src/Toml/Type.hs
  src/Toml/Type/AnyValue.hs
  src/Toml/Type/TOML.hs
  src/Toml/Type/UValue.hs
  src/Toml/Type/Value.hs
  tomland.cabal
Labels: doc

#173 [#50] Add decode.encode = id tests
  test/Test/Toml/BiCode/Property.hs
  test/Test/Toml/BiMap/Property.hs
  test/Test/Toml/Gen.hs
  tomland.cabal
Labels: codec, test

#179 Add TOML type example to haddock
  examples/Playground.hs
  examples/invalid.toml
  src/Toml/Type/TOML.hs
Labels: doc

#178 Add benchmark results and fix some TODOs
  README.md
  src/Toml/Type/Value.hs
  test/Test/Toml/Gen.hs
  test/Test/Toml/PrefixTree/Property.hs
Labels: doc

#181 Improve DecodeException show
  src/Toml/Bi/Code.hs
Labels: refactoring

#182 Prepare for 1.0.0 release
  CHANGELOG.md
  README.md
  src/Toml.hs
  src/Toml/Bi/Code.hs
  tomland.cabal
Labels: doc

#183 Spelling
  src/Toml/Type/Value.hs
Labels: doc
