Repository kowainik/tomland, pull requests merged in 2021-02, with the labels that each got.

#359 [#358] Update parser-combinators bounds
  CHANGELOG.md
  tomland.cabal
Labels: dependencies

#361 [#360] Update copyrights, use headroom
  .headroom.yaml
  headroom-templates/haskell.mustache
  src/Toml.hs
  src/Toml/Codec.hs
  src/Toml/Codec/BiMap.hs
  src/Toml/Codec/BiMap/Conversion.hs
  src/Toml/Codec/Code.hs
  src/Toml/Codec/Combinator.hs
  src/Toml/Codec/Combinator/Common.hs
  src/Toml/Codec/Combinator/Custom.hs
  src/Toml/Codec/Combinator/List.hs
  src/Toml/Codec/Combinator/Map.hs
  src/Toml/Codec/Combinator/Monoid.hs
  src/Toml/Codec/Combinator/Primitive.hs
  src/Toml/Codec/Combinator/Set.hs
  src/Toml/Codec/Combinator/Table.hs
  src/Toml/Codec/Combinator/Time.hs
  src/Toml/Codec/Combinator/Tuple.hs
  src/Toml/Codec/Di.hs
  src/Toml/Codec/Error.hs
  src/Toml/Codec/Generic.hs
  src/Toml/Codec/Types.hs
  src/Toml/Parser.hs
  src/Toml/Parser/Core.hs
  src/Toml/Parser/Item.hs
  src/Toml/Parser/Key.hs
  src/Toml/Parser/String.hs
  src/Toml/Parser/Validate.hs
  src/Toml/Parser/Value.hs
  src/Toml/Type.hs
  src/Toml/Type/AnyValue.hs
  src/Toml/Type/Edsl.hs
  src/Toml/Type/Key.hs
  src/Toml/Type/PrefixTree.hs
  src/Toml/Type/Printer.hs
  src/Toml/Type/TOML.hs
  src/Toml/Type/UValue.hs
  src/Toml/Type/Value.hs
  tomland.cabal
Labels: doc, refactoring

#362 [#329] Add _Hardcoded `TomlBiMap`
  CHANGELOG.md
  examples/Main.hs
  examples/biTest.toml
  src/Toml/Codec/BiMap/Conversion.hs
  src/Toml/Codec/Combinator/Common.hs
  src/Toml/Codec/Combinator/Custom.hs
  test/Test/Toml/Codec/BiMap/Conversion.hs
  test/Test/Toml/Codec/Code.hs
  test/Test/Toml/Codec/Combinator/Custom.hs
Labels: codec

#363 [#186] Implement TOML difference
  CHANGELOG.md
  src/Toml/Codec/Code.hs
  src/Toml/Codec/Error.hs
  src/Toml/Type/PrefixTree.hs
  src/Toml/Type/TOML.hs
  test/Test/Toml/Codec/Code.hs
  test/Test/Toml/Codec/Combinator/Common.hs
  test/Test/Toml/Codec/SmallType.hs
Labels: λ-safe

#365 [#364] Update GHCs minor, update Stack
  .github/workflows/ci.yml
  CHANGELOG.md
  appveyor.yml
  stack.yaml
  tomland.cabal
Labels: CI

#366 [#322] Strip Prefix with DerivingVia TomlTable
  examples/Main.hs
  examples/generic.toml
  src/Toml/Codec/Generic.hs
Labels: generics

#367 Prepare release 1.3.2.0
  CHANGELOG.md
  src/Toml/Codec/BiMap/Conversion.hs
  src/Toml/Codec/Code.hs
  src/Toml/Codec/Combinator/Custom.hs
  src/Toml/Codec/Error.hs
  src/Toml/Codec/Generic.hs
  src/Toml/Type/PrefixTree.hs
  src/Toml/Type/TOML.hs
  tomland.cabal
Labels: doc
